# Generated by Django 5.1.5 on 2025-02-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.cidade')),
            ],
        ),
    ]
