# Generated by Django 5.1.5 on 2025-02-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_pessoa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoas', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
